spring:
  application:
    name: back
  kafka:
    consumer:
      auto-offset-reset: latest
      group-id: p-14017-5
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "com.back.infra.kafka"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer